[font]
size = 15.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

# Make Ctrl+6 (toggle between the current file and the alternate file in Vim) work.
# See https://github.com/alacritty/alacritty/issues/1108.
[[keyboard.bindings]]
chars = "\u001e"
key = "Key6"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
option_as_alt = "Both"
resize_increments = true
